"""схема центра по architecture §5

Revision ID: 00579b2541c6
Revises:
Create Date: 2026-08-07 20:05:45.465294
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "00579b2541c6"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_releases",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.Column(
            "channel",
            sa.Enum("pilot", "stable", name="release_channel", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "released_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("actor", sa.String(length=200), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "scales",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "static", "dynamic", "platform", name="scale_kind", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("driver", sa.String(length=32), nullable=False),
        sa.Column("port_cfg", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("thresholds", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("legacy_ip", sa.String(length=45), nullable=True),
        sa.Column("legacy_port", sa.Integer(), nullable=True),
        sa.Column("legacy_autoscale", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # частичный уникальный индекс: UNIQUE с NULLS DISTINCT пропускал бы дубли
    # маршрута при legacy_autoscale IS NULL, а совсем без legacy-маршрута
    # (все поля NULL) весов может быть сколько угодно
    op.create_index(
        "uq_scales_legacy_route",
        "scales",
        ["legacy_ip", "legacy_port", "legacy_autoscale"],
        unique=True,
        postgresql_where=sa.text("legacy_ip IS NOT NULL"),
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("login", sa.String(length=64), nullable=False),
        sa.Column("pw_hash", sa.String(length=256), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "admin", "dispatcher", "operator", name="user_role", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("site_id", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("login"),
    )
    op.create_table(
        "agents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scale_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=128), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=True),
        sa.Column(
            "channel",
            sa.Enum("pilot", "stable", name="release_channel", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("online", "offline", name="agent_status", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["scale_id"],
            ["scales.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scale_id"),
    )
    op.create_table(
        "cameras",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scale_id", sa.Integer(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("front", "rear", name="camera_role", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("snapshot_url", sa.Text(), nullable=True),
        sa.Column("rtsp_url", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["scale_id"],
            ["scales.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scale_id", "role", name="uq_cameras_scale_role"),
    )
    op.create_table(
        "weighings",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("scale_id", sa.Integer(), nullable=False),
        sa.Column(
            "operation",
            sa.Enum("weighing", "taring", name="operation", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column(
            "code",
            sa.Enum(
                "OK",
                "ERR_AGENT_OFFLINE",
                "ERR_SCALE_OFFLINE",
                "ERR_NOT_ZERO",
                "ERR_VEHICLE_TIMEOUT",
                "ERR_UNSTABLE",
                "ERR_CAMERA",
                "ERR_BUSY",
                "ERR_INTERNAL",
                name="error_code",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("massa", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=8), nullable=False),
        sa.Column("stable", sa.Boolean(), nullable=False),
        sa.Column("weighed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("vehicle_number", sa.String(length=32), nullable=True),
        sa.Column("trailer_number", sa.String(length=32), nullable=True),
        sa.Column("tare_weighing_id", sa.BigInteger(), nullable=True),
        sa.Column("tare_value", sa.Float(), nullable=True),
        sa.Column("netto", sa.Float(), nullable=True),
        sa.Column(
            "source",
            sa.Enum("ais", "local_offline", name="weighing_source", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("operator", sa.String(length=200), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("request_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("storno_of", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["scale_id"],
            ["scales.id"],
        ),
        sa.ForeignKeyConstraint(
            ["storno_of"],
            ["weighings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tare_weighing_id"],
            ["weighings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(
        "ix_weighings_scale_created", "weighings", ["scale_id", "created_at"], unique=False
    )
    op.create_index("ix_weighings_vehicle", "weighings", ["vehicle_number"], unique=False)
    op.create_table(
        "tare_registry",
        sa.Column("vehicle_number", sa.String(length=32), nullable=False),
        sa.Column("weighing_id", sa.BigInteger(), nullable=False),
        sa.Column("tare_value", sa.Float(), nullable=False),
        sa.Column("tared_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["weighing_id"],
            ["weighings.id"],
        ),
        sa.PrimaryKeyConstraint("vehicle_number"),
    )
    op.create_table(
        "weighing_photos",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("weighing_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("front", "rear", name="camera_role", native_enum=False, length=32),
            nullable=False,
        ),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["weighing_id"],
            ["weighings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("weighing_id", "role", name="uq_weighing_photos_role"),
    )
    # ### end Alembic commands ###

    # Правило №2 (неизменяемость) на уровне БД: записанные операции и фото
    # не редактируются и не удаляются даже прямым SQL. Сторнирование — только
    # новой записью со ссылкой storno_of.
    op.execute(
        """
        CREATE FUNCTION forbid_weighing_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION
                'взвешивания не редактируются и не удаляются (правило неизменяемости)';
        END;
        $$ LANGUAGE plpgsql;

        CREATE TRIGGER weighings_immutable
            BEFORE UPDATE OR DELETE ON weighings
            FOR EACH ROW EXECUTE FUNCTION forbid_weighing_mutation();

        CREATE TRIGGER weighing_photos_immutable
            BEFORE UPDATE OR DELETE ON weighing_photos
            FOR EACH ROW EXECUTE FUNCTION forbid_weighing_mutation();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS weighing_photos_immutable ON weighing_photos")
    op.execute("DROP TRIGGER IF EXISTS weighings_immutable ON weighings")
    op.execute("DROP FUNCTION IF EXISTS forbid_weighing_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weighing_photos")
    op.drop_table("tare_registry")
    op.drop_index("ix_weighings_vehicle", table_name="weighings")
    op.drop_index("ix_weighings_scale_created", table_name="weighings")
    op.drop_table("weighings")
    op.drop_table("cameras")
    op.drop_table("agents")
    op.drop_table("users")
    op.drop_table("scales")
    op.drop_table("sites")
    op.drop_table("audit_log")
    op.drop_table("agent_releases")
    # ### end Alembic commands ###
